# Generated by Django 2.2.5 on 2019-10-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-created_at']},
        ),
    ]
