# Generated by Django 2.2.5 on 2019-10-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20191007_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['created_at']},
        ),
    ]
